#!/usr/bin/env python3
"""Build the parts of brand.html that must not drift, and the asset zip.

Three things go stale the moment anyone touches the design system: the
hex values on the page, the contrast figures quoted next to them, and the
list of files offered for download. All three are generated here - the
palette from the brand block in assets/styles.css, the download grid from
the files actually sitting in brand/, and the zip from the same files.

    python3 tools/build_brand_page.py            # rewrite the blocks + zip
    python3 tools/build_brand_page.py --check    # fail if out of date

The prose in brand.html is written by hand; only the two marked blocks
belong to this script. Add an SVG to brand/ and run it, and the page
offers it with its real dimensions, colours and weight.
"""

import glob
import os
import re
import sys
import zipfile

PAGE = "brand.html"
CSS = "assets/styles.css"
ZIP = "downloads/creartbox-brand-assets.zip"

PALETTE_RE = re.compile(
    r"(<!-- BRAND PALETTE · generated by tools/build_brand_page\.py -->\n).*?"
    r"(<!-- /BRAND PALETTE -->)", re.S)
DOWNLOADS_RE = re.compile(
    r"(<!-- BRAND DOWNLOADS · generated by tools/build_brand_page\.py -->\n).*?"
    r"(<!-- /BRAND DOWNLOADS -->)", re.S)

# the palette, in the order the manual presents it, with what each is for
GROUPS = [
    ("Surfaces", [
        ("--sala", "Page ground"),
        ("--foso", "Cards and raised surfaces"),
        ("--filete", "Rules and dividers"),
        ("--filete-alto", "Rules that need to be seen"),
    ]),
    ("Ink", [
        ("--papel", "Headings and primary text"),
        ("--papel-medio", "Body text"),
        ("--papel-dim", "Secondary text"),
        ("--papel-tenue", "The lightest ink allowed on text"),
        ("--papel-mudo", "Rules and icons only, never text"),
    ]),
    ("Signal", [
        ("--senal", "One signal per screen"),
        ("--senal-adar", "Festival ADAR, replacing the signal"),
        ("--sobre-senal", "Text set on the signal"),
    ]),
]


def tokens():
    """Read the brand tokens out of the stylesheet that actually ships."""
    css = open(CSS, encoding="utf-8").read()
    start = css.index("BRAND v1.1")
    block = css[start:css.index("/* Festival ADAR", start)]
    found = dict(re.findall(r"(--[a-z-]+):\s*(#[0-9A-Fa-f]{6});", block))
    missing = [n for _, rows in GROUPS for n, _ in rows if n not in found]
    if missing:
        sys.exit("tokens missing from {}: {}".format(CSS, ", ".join(missing)))
    return found


def luminance(hex_value):
    channels = [int(hex_value[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    channels = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
                for c in channels]
    r, g, b = channels
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def palette_html(tok):
    sala = tok["--sala"]
    out = []
    for heading, rows in GROUPS:
        out.append('      <h3 class="brand-sub">{}</h3>'.format(heading))
        out.append('      <ul class="swatches">')
        for name, use in rows:
            value = tok[name]
            # Only ink and signal carry a ratio. A surface is a ground, not
            # something read against one, and printing "1.0:1" beside
            # --sala would suggest a failure rather than a category error.
            ratio_html = ""
            if heading != "Surfaces":
                against, against_name = (
                    (tok["--senal"], "--senal") if name == "--sobre-senal"
                    else (sala, "--sala"))
                ratio_html = (
                    '<span class="sw-ratio">{:.1f}:1 on '
                    '<span class="sw-mono">{}</span></span>'.format(
                        contrast(value, against), against_name))
            out.append(
                '        <li class="swatch">'
                '<span class="sw-chip" style="background:{value}"></span>'
                '<span class="sw-token">{name}</span>'
                '<span class="sw-hex">{value}</span>'
                '<span class="sw-use">{use}</span>'
                '{ratio_html}'
                '</li>'.format(value=value, name=name, use=use,
                               ratio_html=ratio_html))
        out.append("      </ul>")
    return "\n".join(out) + "\n"


def describe(path):
    """Dimensions, aspect, colours and weight, read off the file."""
    svg = open(path, encoding="utf-8").read()
    box = re.search(r'viewBox="([^"]+)"', svg)
    width = height = None
    if box:
        nums = [float(n) for n in box.group(1).split()]
        if len(nums) == 4:
            width, height = nums[2], nums[3]
    colours = sorted(set(re.findall(r'fill="(#[0-9A-Fa-f]{6})"', svg)))
    return {
        "name": os.path.basename(path),
        "width": width,
        "height": height,
        "aspect": "{:.2f}:1".format(width / height) if width and height else "",
        "colours": colours,
        "kb": os.path.getsize(path) / 1024.0,
        # A mark needs a light card if ANY of its ink is dark. Testing
        # every colour instead missed the two-colour marks: the amber
        # wedge in logo-creartbox-primary is bright, so the black
        # wordmark beside it was being shown black-on-black.
        "needs_light": any(luminance(c) < 0.2 for c in colours) if colours else False,
    }


def downloads_html(assets):
    out = ['      <ul class="asset-grid">']
    for a in assets:
        ground = "asset-on-light" if a["needs_light"] else "asset-on-dark"
        dims = ("{:g} &times; {:g}".format(a["width"], a["height"])
                if a["width"] else "&mdash;")
        swatches = "".join(
            '<span class="asset-dot" style="background:{}" title="{}"></span>'.format(c, c)
            for c in a["colours"])
        out.append(
            '        <li class="asset {ground}">\n'
            '          <div class="asset-prev"><img src="brand/{name}" alt="{name}" loading="lazy"></div>\n'
            '          <div class="asset-meta">\n'
            '            <a class="asset-name" href="brand/{name}" download>{name}</a>\n'
            '            <span class="asset-spec">{dims} &middot; {aspect} &middot; {kb:.1f} KB {swatches}</span>\n'
            '          </div>\n'
            '        </li>'.format(ground=ground, name=a["name"], dims=dims,
                                  aspect=a["aspect"], kb=a["kb"], swatches=swatches))
    out.append("      </ul>")
    return "\n".join(out) + "\n"


def build_zip(check):
    """One archive of every brand file, reproducible so --check is stable."""
    names = sorted(os.path.basename(p) for p in glob.glob("brand/*"))
    if not check:
        os.makedirs(os.path.dirname(ZIP), exist_ok=True)
        with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
            for name in names:
                info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                z.writestr(info, open(os.path.join("brand", name), "rb").read())
        return names, True
    if not os.path.exists(ZIP):
        return names, False
    with zipfile.ZipFile(ZIP) as z:
        return names, sorted(z.namelist()) == names


def main():
    check = "--check" in sys.argv
    src = open(PAGE, encoding="utf-8").read()
    for label, pattern in (("palette", PALETTE_RE), ("downloads", DOWNLOADS_RE)):
        if not pattern.search(src):
            sys.exit("no generated {} block in {}".format(label, PAGE))

    tok = tokens()
    assets = [describe(p) for p in sorted(glob.glob("brand/*.svg"))]

    out = PALETTE_RE.sub(
        lambda m: m.group(1) + palette_html(tok) + m.group(2), src, count=1)
    out = DOWNLOADS_RE.sub(
        lambda m: m.group(1) + downloads_html(assets) + m.group(2), out, count=1)

    names, zip_ok = build_zip(check)

    if check:
        stale = []
        if out != src:
            stale.append("brand.html blocks")
        if not zip_ok:
            stale.append(ZIP)
        if stale:
            print("out of date: {}".format(", ".join(stale)))
            print("\nRun: python3 tools/build_brand_page.py")
            return 1
        print("brand page up to date: {} assets, {} files in the zip".format(
            len(assets), len(names)))
        return 0

    if out != src:
        open(PAGE, "w", encoding="utf-8").write(out)
    print("brand page: {} assets listed, {} files zipped".format(len(assets), len(names)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
