#!/usr/bin/env python3
"""Put the teaser film and a gallery in every event page's About block.

Someone who lands straight on a concert page from a link has never seen
the ensemble. The About CreArtBox section on those pages now carries the
two-minute film and a strip of photographs, so the page introduces
CreArtBox without the visitor having to go looking.

    python3 tools/sync_event_about.py            # rewrite the blocks
    python3 tools/sync_event_about.py --check    # fail if out of date

The prose and the three buttons are left exactly as each page has them;
only the film and the gallery are written here, between markers. The
film reuses the site's existing .video-trigger, so there is no second
player: assets/site.js builds the dialog on any page that needs one.
"""

import glob
import re
import sys

TEASER = "https://vz-a6a9f576-8c5.b-cdn.net/afab56b1-19a9-4053-909c-9c937242907c/playlist.m3u8"
POSTER = "https://vz-a6a9f576-8c5.b-cdn.net/afab56b1-19a9-4053-909c-9c937242907c/thumbnail.jpg"

# a spread of the ensemble's work: chamber music, staged production,
# projection, the festival outdoors
GALLERY = [
    ("ensemble.jpg", "The ensemble in rehearsal"),
    ("arch-echoes.jpg", "Chamber music with projected image"),
    ("feat-circlenoir.jpg", "An audience seated in the round"),
    ("acm-1.jpg", "Architecture of a Common Man"),
    ("arch-folk.jpg", "The New York Series at The DiMenna Center"),
    ("adar.jpg", "Festival ADAR, Asturias"),
]

BLOCK_RE = re.compile(
    r"(<!-- ABOUT MEDIA · generated by tools/sync_event_about\.py -->\n)"
    r".*?"
    r"(<!-- /ABOUT MEDIA -->)", re.S)
LINKS_RE = re.compile(r'(\s*)<div class="about-links">')


def block(prefix):
    shots = "".join(
        '<a class="ab-shot" href="{p}media.html#photos">'
        '<img src="{p}assets/img/{f}" alt="{a}" loading="lazy"></a>'.format(p=prefix, f=f, a=a)
        for f, a in GALLERY)
    return (
        '  <button class="video-trigger ab-film" data-video-src="{src}" '
        'data-video-title="CreArtBox &#183; two minutes">\n'
        '    <span class="video-thumb"><img src="{poster}" alt="Watch the CreArtBox film" '
        'loading="lazy"><span class="video-play" aria-hidden="true"></span></span>\n'
        '    <span class="ab-film-label">Watch &#183; two minutes</span>\n'
        '  </button>\n'
        '  <div class="ab-gallery">{shots}</div>\n'.format(
            src=TEASER, poster=POSTER, shots=shots))


def main():
    check = "--check" in sys.argv
    stale = []

    for path in sorted(glob.glob("concerts/*.html") + glob.glob("archive/*.html")):
        src = open(path, encoding="utf-8").read()
        if "event-about" not in src:
            continue
        prefix = "../"
        wanted = block(prefix)

        if BLOCK_RE.search(src):
            out = BLOCK_RE.sub(lambda m: m.group(1) + wanted + m.group(2), src, count=1)
        else:
            # first run: park it just above the three About buttons
            links = LINKS_RE.search(src)
            if not links:
                print("  !! no .about-links in", path)
                continue
            out = src.replace(
                links.group(0),
                "\n<!-- ABOUT MEDIA · generated by tools/sync_event_about.py -->\n"
                + wanted
                + "<!-- /ABOUT MEDIA -->" + links.group(0), 1)

        if out != src:
            stale.append(path)
            if not check:
                open(path, "w", encoding="utf-8").write(out)

    if check:
        if stale:
            print("About blocks out of date in {} page(s):".format(len(stale)))
            for p in stale[:10]:
                print("  -", p)
            print("\nRun: python3 tools/sync_event_about.py")
            return 1
        print("About blocks up to date")
        return 0

    print("updated {} page(s)".format(len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
