#!/usr/bin/env python3
"""Point the home page's "next event" block at the next event in the calendar.

The block used to be written by hand, so it went on advertising Festival
ADAR 2026 for a month after the festival had finished. It is now built
from the first row of concerts.html and from that concert's own page, so
the home page cannot disagree with the calendar or fall into the past.

    python3 tools/sync_next_event.py            # rewrite the block
    python3 tools/sync_next_event.py --check    # fail if out of date

Everything shown comes from the concert page: its series, title, hero
image, opening paragraph and sidebar facts. To change what the home page
says, edit the concert page and run this again. Rows are in date order,
so keeping the calendar tidy is what keeps this correct - move a concert
to the archive once it has happened and the next one moves up.
"""

import re
import sys

HOME = "index.html"
INDEX = "concerts.html"

BLOCK_RE = re.compile(
    r"(<!-- NEXT EVENT · generated by tools/sync_next_event\.py -->\n)"
    r".*?"
    r"(<!-- /NEXT EVENT -->)",
    re.S,
)
ROW_RE = re.compile(r'<tr data-concert-series="[^"]+">.*?</tr>', re.S)
HREF_RE = re.compile(r'class="title-cell"><a href="([^"]+)"')
SERIES_RE = re.compile(r'class="event-series">(.*?)</div>', re.S)
TITLE_RE = re.compile(r'class="event-title">(.*?)</h1>', re.S)
HERO_RE = re.compile(r'class="concert-hero"><img src="([^"]+)"')
DESC_RE = re.compile(r'<section class="event-description">(.*?)</section>', re.S)
PARA_RE = re.compile(r"<p>(.*?)</p>", re.S)
META_RE = re.compile(
    r'<div class="meta-h">(.*?)</div>\s*<div class="meta-v">(.*?)</div>', re.S
)
MONTH_RE = re.compile(r"^([A-Z][a-z]+)\b.*?(\d{4})\s*$")


def strip_tags(fragment):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", fragment)).strip()


def next_event():
    """The first calendar row, read back off the concert's own page."""
    row = ROW_RE.search(open(INDEX, encoding="utf-8").read())
    if not row:
        sys.exit("no concert rows found in " + INDEX)
    href = HREF_RE.search(row.group(0))
    if not href:
        sys.exit("the first calendar row has no link to a concert page")
    path = href.group(1)
    page = open(path, encoding="utf-8").read()

    meta = {}
    for head, value in META_RE.findall(page):
        meta[strip_tags(head)] = value.strip()

    return {
        "path": path,
        "series": strip_tags(SERIES_RE.search(page).group(1)),
        "title": strip_tags(TITLE_RE.search(page).group(1)),
        # the home page sits a level above the concert pages
        "hero": HERO_RE.search(page).group(1).replace("../", "", 1),
        "blurb": PARA_RE.search(DESC_RE.search(page).group(1)).group(1).strip(),
        "meta": meta,
    }


def month_of(when):
    """"October 5 - 9, 2026" -> "October 2026"."""
    m = MONTH_RE.match(strip_tags(when))
    return "{} {}".format(m.group(1), m.group(2)) if m else strip_tags(when)


def venue_rows(meta):
    """The sidebar facts, as the home page's own table rows."""
    rows = []
    for label, key in (("Dates", "When"), ("Venue", "Venue"), ("Series", "Series")):
        if key not in meta:
            continue
        value = meta[key]
        if key == "Venue":
            # the page writes "Name<br><small>address</small>"
            name, _, address = value.partition("<br>")
            rows.append((label, strip_tags(name)))
            if strip_tags(address):
                rows.append(("Where", strip_tags(address)))
        else:
            rows.append((label, strip_tags(value)))
    return rows


def render(ev):
    series = ev["series"]
    head, sep, tail = series.rpartition(" · ")
    caption = (head + sep + "<em>" + tail + "</em>") if sep else "<em>" + series + "</em>"

    cells = "\n".join(
        '            <tr style="border-top:1px solid var(--rule)">'
        '<td style="padding:14px 16px 14px 0;width:8em"><span class="label">{}</span></td>'
        '<td style="padding:14px 0;font-size:17px{}">{}</td></tr>'.format(
            label, ";font-weight:500" if label == "Dates" else ";font-style:italic", value
        )
        for label, value in venue_rows(ev["meta"])
    )

    return """<section class="section tinted">
  <div class="wrap">
    <div class="section-title">
      <hr class="rule">
      <div class="head"><span class="label">The next event</span><span class="bar"></span><span class="label ital">{caption}.</span></div>
      <hr class="rule">
      <h2 class="h-feature">{month}</h2>
    </div>

    <div class="two-col-balanced" style="gap:48px;align-items:center">
      <figure>
        <div class="imedia" style="aspect-ratio:4/3"><img src="{hero}" alt="{title}"></div>
      </figure>
      <div>
        <h3 class="h-title" style="margin:0;font-size:34px">{title}</h3>
        <p class="body-l" style="margin:14px 0 0">{blurb}</p>
        <table style="width:100%;border-collapse:collapse;margin-top:20px">
          <tbody>
{cells}
          </tbody>
        </table>
        <div style="display:flex;gap:10px;margin-top:24px;flex-wrap:wrap">
          <a href="{path}" class="btn btn-stamp">Full details <span class="ar">&#8594;</span></a>
          <a href="concerts.html" class="btn">See the full calendar <span class="ar">&#8594;</span></a>
        </div>
      </div>
    </div>
  </div>
</section>
""".format(
        caption=caption,
        month=month_of(ev["meta"].get("When", "")),
        hero=ev["hero"],
        title=ev["title"],
        blurb=ev["blurb"],
        cells=cells,
        path=ev["path"],
    )


def main():
    check = "--check" in sys.argv
    src = open(HOME, encoding="utf-8").read()
    if not BLOCK_RE.search(src):
        sys.exit(
            "no generated block in {}. Wrap the next-event section in\n"
            "  <!-- NEXT EVENT · generated by tools/sync_next_event.py -->\n"
            "  ...\n"
            "  <!-- /NEXT EVENT -->".format(HOME)
        )

    ev = next_event()
    out = BLOCK_RE.sub(lambda m: m.group(1) + render(ev) + m.group(2), src, count=1)

    if check:
        if out != src:
            print('home page is not showing the next event ("{}", {})'.format(
                ev["title"], ev["meta"].get("When", "")))
            print("\nRun: python3 tools/sync_next_event.py")
            return 1
        print('next event up to date: {} · {}'.format(
            ev["title"], ev["meta"].get("When", "")))
        return 0

    if out != src:
        open(HOME, "w", encoding="utf-8").write(out)
        print('next event: {} · {}'.format(ev["title"], ev["meta"].get("When", "")))
    else:
        print("already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
