#!/usr/bin/env python3
"""Give the home page the next production, and what follows it.

The block used to show whatever came first in the calendar, which meant a
masterclass week could outrank the concert the ensemble is selling seats
for. It now leads with the next of CreArtBox's own productions - the rows
the calendar marks as new productions - and lists the next few dates
underneath, so the residency or the touring date is still there without
taking the big slot.

    python3 tools/sync_next_event.py            # rewrite the block
    python3 tools/sync_next_event.py --check    # fail if out of date

Everything comes from the calendar and from the concert's own page: its
series, title, hero image, opening paragraph, sidebar facts, ticket link
and, if one has been published, its programme booklet. To change what the
home page says, edit the concert page and run this again.
"""

import os
import re
import sys

HOME = "index.html"
INDEX = "concerts.html"
UP_NEXT = 3          # how many dates to list under the featured production

BLOCK_RE = re.compile(
    r"(<!-- NEXT EVENT · generated by tools/sync_next_event\.py -->\n)"
    r".*?"
    r"(<!-- /NEXT EVENT -->)",
    re.S,
)
ROW_RE = re.compile(r'<tr[^>]*data-concert-series="[^"]+">.*?</tr>', re.S)
HREF_RE = re.compile(r'class="title-cell"><a href="([^"]+)"')
ROW_TITLE_RE = re.compile(r'class="title-cell"><a[^>]*>(.*?)</a>', re.S)
ROW_NUM_RE = re.compile(r'<span class="num">(\d+)</span>')
ROW_MONTH_RE = re.compile(r'<span style="display:block;font-size:14px[^"]*">([^<]*)</span>')
ROW_WHERE_RE = re.compile(r'<td class="where">(.*?)</td>', re.S)
SERIES_RE = re.compile(r'class="event-series">(.*?)</div>', re.S)
TITLE_RE = re.compile(r'class="event-title">(.*?)</h1>', re.S)
HERO_RE = re.compile(r'class="concert-hero"><img src="([^"]+)"')
DESC_RE = re.compile(r'<section class="event-description">(.*?)</section>', re.S)
PARA_RE = re.compile(r"<p>(.*?)</p>", re.S)
META_RE = re.compile(
    r'<div class="meta-h">(.*?)</div>\s*<div class="meta-v">(.*?)</div>', re.S
)
TICKETS_RE = re.compile(r'href="(https://www\.eventbrite\.com/e/[^"]+)"[^>]*class="btn btn-ticket"')
MONTH_RE = re.compile(r"^([A-Z][a-z]+)\b.*?(\d{4})\s*$")


def strip_tags(fragment):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", fragment)).strip()


def rows():
    return ROW_RE.findall(open(INDEX, encoding="utf-8").read())


def read_page(path):
    page = open(path, encoding="utf-8").read()
    meta = {}
    for head, value in META_RE.findall(page):
        meta[strip_tags(head)] = value.strip()
    tickets = TICKETS_RE.search(page)
    # a programme booklet is published under the concert's own name
    slug = os.path.splitext(os.path.basename(path))[0]
    booklet = "programs/{}.html".format(slug)
    return {
        "path": path,
        "series": strip_tags(SERIES_RE.search(page).group(1)),
        "title": strip_tags(TITLE_RE.search(page).group(1)),
        # the home page sits a level above the concert pages
        "hero": HERO_RE.search(page).group(1).replace("../", "", 1),
        "blurb": PARA_RE.search(DESC_RE.search(page).group(1)).group(1).strip(),
        "meta": meta,
        "tickets": tickets.group(1) if tickets else None,
        "booklet": booklet if os.path.exists(booklet) else None,
    }


def featured_row(all_rows):
    """The next of the ensemble's own productions, else the next date."""
    for row in all_rows:
        if "data-new-production" in row:
            return row
    return all_rows[0]


def small(row):
    """Date, title and place for one of the lines under the feature."""
    href = HREF_RE.search(row)
    if not href:
        return None
    num = ROW_NUM_RE.search(row)
    month = ROW_MONTH_RE.search(row)
    where = ROW_WHERE_RE.search(row)
    return {
        "path": href.group(1),
        "title": strip_tags(ROW_TITLE_RE.search(row).group(1)),
        "date": "{} {}".format(num.group(1) if num else "", month.group(1) if month else "").strip(),
        "where": strip_tags(where.group(1).split("<br>")[0]) if where else "",
    }


def month_of(when):
    """"October 30, 2026 · 7:30 pm" -> "October 2026"."""
    m = MONTH_RE.match(re.split(r"·", strip_tags(when))[0].strip())
    return "{} {}".format(m.group(1), m.group(2)) if m else strip_tags(when)


def venue_rows(meta):
    """The sidebar facts, as the home page's own table rows."""
    out = []
    for label, key in (("Dates", "When"), ("Venue", "Venue"), ("Series", "Series")):
        if key not in meta:
            continue
        value = meta[key]
        if key == "Venue":
            # the page writes "Name<br><small>address</small>"
            name, _, address = value.partition("<br>")
            out.append((label, strip_tags(name)))
            if strip_tags(address):
                out.append(("Where", strip_tags(address)))
        else:
            out.append((label, strip_tags(value)))
    return out


def render(ev, coming):
    series = ev["series"]
    head, sep, tail = series.rpartition(" · ")
    caption = (head + sep + "<em>" + tail + "</em>") if sep else "<em>" + series + "</em>"

    cells = "\n".join(
        '            <tr style="border-top:1px solid var(--rule)">'
        '<td style="padding:14px 16px 14px 0;width:8em"><span class="label">{}</span></td>'
        '<td style="padding:14px 0;font-size:17px{}">{}</td></tr>'.format(
            label, ";font-weight:500" if label == "Dates" else ";font-style:italic", value
        )
        for label, value in venue_rows(ev["meta"])
    )

    # buying a seat is the loud button wherever a seat can be bought
    buttons = []
    if ev["tickets"]:
        buttons.append('<a href="{}" class="btn btn-stamp btn-l" target="_blank" '
                       'rel="noopener">Get tickets on Eventbrite <span class="ar">&#8594;</span></a>'
                       .format(ev["tickets"]))
        buttons.append('<a href="{}" class="btn btn-l">Full details</a>'.format(ev["path"]))
    else:
        buttons.append('<a href="{}" class="btn btn-stamp btn-l">Full details '
                       '<span class="ar">&#8594;</span></a>'.format(ev["path"]))
    if ev["booklet"]:
        buttons.append('<a href="{}" class="btn btn-l">Read the programme</a>'.format(ev["booklet"]))

    lines = "\n".join(
        '        <li><a href="{path}">'
        '<span class="un-date">{date}</span>'
        '<span class="un-title">{title}</span>'
        '<span class="un-where">{where}</span></a></li>'.format(**c)
        for c in coming
    )
    strip = ""
    if coming:
        strip = """
    <div class="upnext">
      <div class="upnext-head"><span class="label">Also coming up</span><hr class="rule"></div>
      <ul class="upnext-list">
{lines}
      </ul>
    </div>
""".format(lines=lines)

    return """<section class="section tinted">
  <div class="wrap">
    <div class="section-title">
      <hr class="rule">
      <div class="head"><span class="label">Next production</span><span class="bar"></span><span class="label ital">{caption}.</span></div>
      <hr class="rule">
      <h2 class="h-feature">{month}</h2>
    </div>

    <div class="two-col-balanced" style="gap:48px;align-items:center">
      <figure>
        <div class="imedia" style="aspect-ratio:4/3"><img src="{hero}" alt="{title}"></div>
      </figure>
      <div>
        <h3 class="h-title next-title">{title}</h3>
        <p class="body-l" style="margin:14px 0 0">{blurb}</p>
        <table style="width:100%;border-collapse:collapse;margin-top:20px">
          <tbody>
{cells}
          </tbody>
        </table>
        <div style="display:flex;gap:10px;margin-top:24px;flex-wrap:wrap">
          {buttons}
        </div>
      </div>
    </div>
{strip}  </div>
</section>
""".format(
        caption=caption,
        month=month_of(ev["meta"].get("When", "")),
        hero=ev["hero"],
        title=ev["title"],
        blurb=ev["blurb"],
        cells=cells,
        buttons="\n          ".join(buttons),
        strip=strip,
    )


def main():
    check = "--check" in sys.argv
    src = open(HOME, encoding="utf-8").read()
    if not BLOCK_RE.search(src):
        sys.exit(
            "no generated block in {}. Wrap the next-event section in\n"
            "  <!-- NEXT EVENT · generated by tools/sync_next_event.py -->\n"
            "  ...\n"
            "  <!-- /NEXT EVENT -->".format(HOME)
        )

    all_rows = rows()
    if not all_rows:
        sys.exit("no concert rows found in " + INDEX)
    lead = featured_row(all_rows)
    href = HREF_RE.search(lead)
    if not href:
        sys.exit("the featured calendar row has no link to a concert page")

    ev = read_page(href.group(1))
    coming = []
    for row in all_rows:
        if row is lead or len(coming) >= UP_NEXT:
            continue
        item = small(row)
        if item:
            coming.append(item)

    out = BLOCK_RE.sub(lambda m: m.group(1) + render(ev, coming) + m.group(2), src, count=1)

    if check:
        if out != src:
            print('home page is not leading with "{}"'.format(ev["title"]))
            print("\nRun: python3 tools/sync_next_event.py")
            return 1
        print("home page leads with: {} · {}".format(
            ev["title"], ev["meta"].get("When", "")))
        return 0

    if out != src:
        open(HOME, "w", encoding="utf-8").write(out)
        print("next production: {} · {}".format(
            ev["title"], ev["meta"].get("When", "")))
        print("also coming up: " + ", ".join(c["title"] for c in coming))
    else:
        print("already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
